import type { AgentContract } from '@projectx/shared';

export interface SpecialistDefinition {
  readonly agentId: string;
  readonly implementationKey: string;
  readonly contract: Omit<AgentContract, 'agentId' | 'version' | 'lifecycle' | 'createdAt' | 'updatedAt'> & { version?: string };
}

export const SYSTEM_SPECIALIST_DEFINITIONS: SpecialistDefinition[] = [
  {
    agentId: 'research-agent',
    implementationKey: 'specialist.research.v1',
    contract: {
      name: 'Research Specialist',
      role: 'researcher',
      description: 'Researches target accounts, markets, and companies using structured evidence.',
      capabilities: ['research', 'company_research', 'market_research'],
      tools: ['search', 'knowledge_read'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.25, maxTokensPerTask: 8000 },
      memoryPolicy: { read: ['research'], write: ['research'], validationRequired: true },
      knowledgePolicy: { read: ['public', 'tenant'], write: [] },
      autonomyLevelDefault: 3,
      evaluationPolicy: { criteria: ['coverage', 'source_quality', 'recency'], minScore: 0.7 },
      owner: 'system',
    },
  },
  {
    agentId: 'icp-qualification-agent',
    implementationKey: 'specialist.icp-qualification.v1',
    contract: {
      name: 'ICP Qualification Specialist',
      role: 'qualifier',
      description: 'Scores an account or lead against the ideal customer profile.',
      capabilities: ['icp_qualification', 'account_fit_scoring'],
      tools: ['knowledge_read'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.15, maxTokensPerTask: 4000 },
      memoryPolicy: { read: ['icp'], write: ['icp_score'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 3,
      evaluationPolicy: { criteria: ['fit_confidence', 'evidence_strength'], minScore: 0.6 },
      owner: 'system',
    },
  },
  {
    agentId: 'lead-qualification-agent',
    implementationKey: 'specialist.lead-qualification.v1',
    contract: {
      name: 'Lead Qualification Specialist',
      role: 'qualifier',
      description: 'Scores and qualifies individual leads based on profile, intent, and engagement.',
      capabilities: ['lead_qualification', 'lead_scoring'],
      tools: ['knowledge_read', 'crm_read'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.15, maxTokensPerTask: 4000 },
      memoryPolicy: { read: ['lead'], write: ['lead_score'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 3,
      evaluationPolicy: { criteria: ['fit', 'authority', 'need', 'timing'], minScore: 0.6 },
      owner: 'system',
    },
  },
  {
    agentId: 'buying-signal-agent',
    implementationKey: 'specialist.buying-signal.v1',
    contract: {
      name: 'Buying Signal Specialist',
      role: 'analyst',
      description: 'Detects and interprets buying signals and intent from signals and research.',
      capabilities: ['buying_signal_detection', 'intent_analysis'],
      tools: ['knowledge_read', 'signal_read'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.2, maxTokensPerTask: 6000 },
      memoryPolicy: { read: ['signals'], write: ['signals'], validationRequired: true },
      knowledgePolicy: { read: ['tenant', 'public'], write: [] },
      autonomyLevelDefault: 3,
      evaluationPolicy: { criteria: ['signal_strength', 'relevance', 'confidence'], minScore: 0.65 },
      owner: 'system',
    },
  },
  {
    agentId: 'outreach-strategist-agent',
    implementationKey: 'specialist.outreach-strategist.v1',
    contract: {
      name: 'Outreach Strategist',
      role: 'strategist',
      description: 'Designs outreach strategy, channel selection, and sequence structure.',
      capabilities: ['outreach_strategy', 'channel_selection', 'sequence_design'],
      tools: ['knowledge_read'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.25, maxTokensPerTask: 6000 },
      memoryPolicy: { read: ['outreach', 'strategy'], write: ['strategy'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 3,
      evaluationPolicy: { criteria: ['relevance', 'compliance', 'personalization'], minScore: 0.7 },
      owner: 'system',
    },
  },
  {
    agentId: 'outreach-writer-agent',
    implementationKey: 'specialist.outreach-writer.v1',
    contract: {
      name: 'Outreach Writer',
      role: 'writer',
      description: 'Drafts and personalizes outreach messages for a specific channel and recipient.',
      capabilities: ['outreach_writing', 'message_drafting', 'personalization'],
      tools: ['knowledge_read', 'output_validate'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'generation', maxCostPerTaskUsd: 0.25, maxTokensPerTask: 4000 },
      memoryPolicy: { read: ['outreach', 'research'], write: ['draft'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 2,
      evaluationPolicy: { criteria: ['clarity', 'tone', 'compliance', 'cta'], minScore: 0.75 },
      owner: 'system',
    },
  },
  {
    agentId: 'conversation-agent',
    implementationKey: 'specialist.conversation.v1',
    contract: {
      name: 'Conversation Specialist',
      role: 'conversationalist',
      description: 'Handles replies, objections, and conversation continuation within policy.',
      capabilities: ['conversation', 'reply_handling', 'objection_response'],
      tools: ['knowledge_read', 'output_validate'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.2, maxTokensPerTask: 6000 },
      memoryPolicy: { read: ['conversation'], write: ['conversation'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 2,
      evaluationPolicy: { criteria: ['coherence', 'safety', 'helpfulness'], minScore: 0.75 },
      owner: 'system',
    },
  },
  {
    agentId: 'meeting-agent',
    implementationKey: 'specialist.meeting.v1',
    contract: {
      name: 'Meeting Specialist',
      role: 'coordinator',
      description: 'Coordinates meeting scheduling and calendar availability within policy.',
      capabilities: ['meeting_scheduling', 'calendar_coordination'],
      tools: ['calendar_read', 'output_validate'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.15, maxTokensPerTask: 4000 },
      memoryPolicy: { read: ['calendar'], write: ['meeting'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 2,
      evaluationPolicy: { criteria: ['availability_match', 'policy_compliance'], minScore: 0.7 },
      owner: 'system',
    },
  },
  {
    agentId: 'crm-agent',
    implementationKey: 'specialist.crm.v1',
    contract: {
      name: 'CRM Specialist',
      role: 'operator',
      description: 'Synchronizes contacts, activities, and outcomes with the CRM system.',
      capabilities: ['crm_sync', 'contact_update', 'activity_logging'],
      tools: ['crm_read', 'crm_write'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.1, maxTokensPerTask: 4000 },
      memoryPolicy: { read: ['crm'], write: ['crm'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 2,
      evaluationPolicy: { criteria: ['data_integrity', 'compliance'], minScore: 0.8 },
      owner: 'system',
    },
  },
  {
    agentId: 'follow-up-nurture-agent',
    implementationKey: 'specialist.follow-up-nurture.v1',
    contract: {
      name: 'Follow-up / Nurture Specialist',
      role: 'nurturer',
      description: 'Plans follow-ups and nurture sequences to re-engage prospects.',
      capabilities: ['follow_up', 'nurture', 're_engagement'],
      tools: ['knowledge_read', 'output_validate'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.2, maxTokensPerTask: 4000 },
      memoryPolicy: { read: ['outreach', 'engagement'], write: ['nurture_plan'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 3,
      evaluationPolicy: { criteria: ['timing', 'relevance', 'non_intrusiveness'], minScore: 0.7 },
      owner: 'system',
    },
  },
  {
    agentId: 'compliance-safety-agent',
    implementationKey: 'specialist.compliance-safety.v1',
    contract: {
      name: 'Compliance / Safety Specialist',
      role: 'reviewer',
      description: 'Reviews content and actions for domain-specific compliance and safety, but does not override Control Plane authority.',
      capabilities: ['compliance_review', 'safety_review', 'policy_check'],
      tools: ['knowledge_read', 'output_validate'],
      policies: [],
      modelPolicy: { preferredModelFamily: 'reasoning', maxCostPerTaskUsd: 0.15, maxTokensPerTask: 4000 },
      memoryPolicy: { read: ['compliance', 'policy'], write: ['compliance_review'], validationRequired: true },
      knowledgePolicy: { read: ['tenant'], write: [] },
      autonomyLevelDefault: 1,
      evaluationPolicy: { criteria: ['no_pii', 'no_disallowed_claims', 'tone_safe'], minScore: 0.85 },
      owner: 'system',
    },
  },
];
