variable "project_name" {
  type        = string
  description = "Short project name used in resource naming"
  default     = "projectx"
}

variable "environment" {
  type        = string
  description = "Environment name"
  default     = "prod"
}

variable "location" {
  type        = string
  description = "Azure region"
  default     = "westeurope"
}

variable "domain_name" {
  type        = string
  description = "Production API custom domain (e.g. projectx.example.com)"
  default     = ""
}

variable "api_image" {
  type        = string
  description = "API container image (set by CI/CD)"
}

variable "worker_image" {
  type        = string
  description = "Temporal worker container image (set by CI/CD)"
}

variable "postgresql_admin_user" {
  type        = string
  description = "PostgreSQL admin username"
  default     = "projectxadmin"
}

variable "temporal_address" {
  type        = string
  description = "Temporal frontend address (generated by IaC or provided for Temporal Cloud)"
  default     = ""
}

variable "temporal_namespace" {
  type        = string
  description = "Temporal namespace (e.g. quickstart-projectx-test.rpxgu)"
  default     = ""
}

variable "temporal_api_key_secret_id" {
  type        = string
  description = "Versioned or versionless ID of the Azure Key Vault secret holding TEMPORAL_API_KEY"
  default     = ""
  sensitive   = true
}

variable "vnet_address_space" {
  type        = string
  description = "VNet CIDR"
  default     = "10.0.0.0/16"
}
