variable "project_name" {
  type        = string
  description = "Short project name used in resource naming"
  default     = "projectx"
}

variable "environment" {
  type        = string
  description = "Environment name"
  default     = "prod"
}

variable "location" {
  type        = string
  description = "Azure region"
  default     = "westeurope"
}

variable "domain_name" {
  type        = string
  description = "Production API custom domain (e.g. projectx.example.com)"
  default     = ""
}

variable "api_image" {
  type        = string
  description = "API container image (set by CI/CD)"
  default     = ""

  validation {
    condition     = !var.enable_application_runtime || var.api_image != ""
    error_message = "api_image is required when enable_application_runtime is true"
  }
}

variable "worker_image" {
  type        = string
  description = "Temporal worker container image (set by CI/CD)"
  default     = ""

  validation {
    condition     = !var.enable_application_runtime || var.worker_image != ""
    error_message = "worker_image is required when enable_application_runtime is true"
  }
}

variable "postgresql_admin_user" {
  type        = string
  description = "PostgreSQL admin username"
  default     = "projectxadmin"
}

variable "temporal_address" {
  type        = string
  description = "Temporal frontend address (generated by IaC or provided for Temporal Cloud)"
  default     = ""
}

variable "temporal_namespace" {
  type        = string
  description = "Temporal namespace (e.g. quickstart-projectx-test.rpxgu)"
  default     = ""
}

variable "temporal_api_key_secret_id" {
  type        = string
  description = "Versioned or versionless ID of the Azure Key Vault secret holding TEMPORAL_API_KEY"
  default     = ""
  sensitive   = true
}

variable "vnet_address_space" {
  type        = string
  description = "VNet CIDR"
  default     = "10.0.0.0/16"
}

variable "enable_migration_bootstrap" {
  type        = bool
  description = "If true, create the one-shot migration Container App Job and identity. Set to false after bootstrap."
  default     = false
}

variable "enable_application_runtime" {
  type        = bool
  description = "If true, create the API and worker Container Apps. Only valid after database-url is available."
  default     = false

  validation {
    condition     = !var.enable_application_runtime || (var.database_url_secret_id != "" && !var.enable_migration_bootstrap)
    error_message = "enable_application_runtime requires a non-empty database_url_secret_id and enable_migration_bootstrap must be false"
  }
}

variable "migration_image" {
  type        = string
  description = "Migration bootstrap container image (set by CI/CD)"
  default     = ""
}

variable "database_url_secret_id" {
  type        = string
  description = "Versionless ID of the Azure Key Vault secret holding the runtime DATABASE_URL"
  default     = ""
}
