import type { TenantContext } from '@projectx/domain';
import type { AgentContract, CapabilityId } from '@projectx/shared';
import type { IAgentRegistry } from '@projectx/ai-runtime';

export const RESEARCH_AGENT_CONTRACTS: AgentContract[] = [
  {
    agentId: 'research-orchestrator',
    version: '1.0.0',
    name: 'Research Orchestrator',
    role: 'orchestrator',
    description: 'Runs the end-to-end research and lead generation pipeline as a mission task.',
    capabilities: ['execute-research-pipeline'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 5, maxTokensPerTask: 10_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    agentId: 'account-discovery-agent',
    version: '1.0.0',
    name: 'Account Discovery Agent',
    role: 'researcher',
    description: 'Discovers accounts matching an ICP profile.',
    capabilities: ['discover-accounts'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 2, maxTokensPerTask: 5_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    agentId: 'company-intelligence-agent',
    version: '1.0.0',
    name: 'Company Intelligence Agent',
    role: 'researcher',
    description: 'Gathers firmographic and technographic intelligence.',
    capabilities: ['company-intelligence'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 2, maxTokensPerTask: 5_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    agentId: 'contact-discovery-agent',
    version: '1.0.0',
    name: 'Contact Discovery Agent',
    role: 'researcher',
    description: 'Discovers contacts for an account.',
    capabilities: ['discover-contacts'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 2, maxTokensPerTask: 5_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    agentId: 'contact-enrichment-agent',
    version: '1.0.0',
    name: 'Contact Enrichment Agent',
    role: 'researcher',
    description: 'Validates and enriches contact data.',
    capabilities: ['enrich-contact'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 1, maxTokensPerTask: 3_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    agentId: 'signal-detection-agent',
    version: '1.0.0',
    name: 'Buying Signal Detection Agent',
    role: 'researcher',
    description: 'Detects buying and intent signals.',
    capabilities: ['detect-buying-signals'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 2, maxTokensPerTask: 5_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    agentId: 'icp-match-agent',
    version: '1.0.0',
    name: 'ICP Match Agent',
    role: 'evaluator',
    description: 'Evaluates account fit against an ICP profile.',
    capabilities: ['evaluate-icp-match'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 1, maxTokensPerTask: 3_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    agentId: 'lead-scoring-agent',
    version: '1.0.0',
    name: 'Lead Scoring Agent',
    role: 'evaluator',
    description: 'Composes ICP, signal, and evidence scores into a lead score.',
    capabilities: ['score-lead'],
    tools: [],
    policies: [],
    modelPolicy: { preferredModelFamily: 'stub', maxCostPerTaskUsd: 1, maxTokensPerTask: 3_000 },
    memoryPolicy: { read: [], write: [], validationRequired: false },
    knowledgePolicy: { read: [], write: [] },
    autonomyLevelDefault: 0.5,
    evaluationPolicy: { criteria: [], minScore: 0 },
    lifecycle: 'ACTIVE',
    owner: 'system',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export class IntelligenceAgentRegistry implements IAgentRegistry {
  async getAgent(_ctx: TenantContext, agentId: string, _version?: string): Promise<AgentContract | null> {
    return RESEARCH_AGENT_CONTRACTS.find((a) => a.agentId === agentId) ?? null;
  }

  async getCapability(_tenantId: string, capabilityId: string): Promise<{ capabilityId: CapabilityId; allowedTools: string[] } | null> {
    const capabilities: Record<string, string[]> = {
      'execute-research-pipeline': [],
      'discover-accounts': [],
      'company-intelligence': [],
      'discover-contacts': [],
      'enrich-contact': [],
      'detect-buying-signals': [],
      'evaluate-icp-match': [],
      'score-lead': [],
    };
    return capabilityId in capabilities
      ? { capabilityId: capabilityId as CapabilityId, allowedTools: capabilities[capabilityId] }
      : null;
  }
}
