export type MessageExecutionStatus =
  | 'PENDING'
  | 'DRAFTING'
  | 'PENDING_APPROVAL'
  | 'APPROVED'
  | 'SENDING'
  | 'PROVIDER_ACCEPTED'
  | 'DELIVERY_PENDING'
  | 'DELIVERED'
  | 'OPENED'
  | 'REPLIED'
  | 'BOUNCED'
  | 'FAILED_PRE_SUBMISSION'
  | 'DELIVERY_FAILED'
  | 'DELIVERY_UNKNOWN'
  | 'REQUIRES_RECONCILIATION'
  | 'FAILED'
  | 'CANCELLED';

export const MESSAGE_EXECUTION_STATE_TRANSITIONS: Record<MessageExecutionStatus, MessageExecutionStatus[]> = {
  PENDING: ['DRAFTING'],
  DRAFTING: ['PENDING_APPROVAL', 'FAILED'],
  PENDING_APPROVAL: ['APPROVED', 'FAILED'],
  APPROVED: ['SENDING'],
  SENDING: ['PROVIDER_ACCEPTED', 'FAILED_PRE_SUBMISSION', 'DELIVERY_UNKNOWN', 'REQUIRES_RECONCILIATION'],
  PROVIDER_ACCEPTED: ['DELIVERY_PENDING'],
  DELIVERY_PENDING: ['DELIVERED', 'DELIVERY_FAILED', 'DELIVERY_UNKNOWN', 'REQUIRES_RECONCILIATION'],
  DELIVERED: ['OPENED'],
  OPENED: ['REPLIED'],
  REPLIED: [],
  BOUNCED: [],
  FAILED_PRE_SUBMISSION: [],
  DELIVERY_FAILED: [],
  DELIVERY_UNKNOWN: [],
  REQUIRES_RECONCILIATION: [],
  FAILED: [],
  CANCELLED: [],
};

export function canTransitionMessageExecution(from: MessageExecutionStatus, to: MessageExecutionStatus): boolean {
  return MESSAGE_EXECUTION_STATE_TRANSITIONS[from].includes(to);
}
